#!/bin/sh

opcode=$1
cmd=$2
args=$3


setup_ap() {
    read macaddr </sys/class/net/ra0/address
    serialnum=$(python3 - <<'__END_PYTHON'
try:
    with open("/media/bootscript/serialnumber2.txt") as f:
        print("{:0>13}".format(f.readline().strip().upper()))
except FileNotFoundError:
    try:
        with open("/media/bootscript/serialnumber.txt") as f:
            # hex format
            print("{:0>13d}".format(int(f.readline().strip(), 16)))
    except Exception as ex:
        print("Failed to get serial")
__END_PYTHON
)

    if [ -z "$serialnum" ]; then
        echo "Error: No serial number"
        exit 1
    fi

    macaddrup="$(echo $macaddr | tr '[:lower:]' '[:upper:]')"
    password=$(echo -n $serialnum | sha256sum)

    # Chop the password town to the length allowed by WPA2:
    password=${password:0:63}

    if grep -q SSID1= /etc/wireless/mediatek/mt7663/mt7663.1.dat && grep -q WPAPSK1= /etc/wireless/mediatek/mt7663/mt7663.1.dat ; then
	sed -i "s/SSID1=.*/SSID1=VIVINT_HUB_${serialnum}/" /etc/wireless/mediatek/mt7663/mt7663.1.dat
	sed -i "s/WPAPSK1=.*/WPAPSK1=${password}/" /etc/wireless/mediatek/mt7663/mt7663.1.dat
    else
	cp /etc/wireless/mediatek/mt7663/mt7663.1.dat_org /etc/wireless/mediatek/mt7663/mt7663.1.dat
	sed -i "s/SSID1=.*/SSID1=VIVINT_HUB_${serialnum}/" /etc/wireless/mediatek/mt7663/mt7663.1.dat
	sed -i "s/WPAPSK1=.*/WPAPSK1=${password}/" /etc/wireless/mediatek/mt7663/mt7663.1.dat
    fi
}


ap_mode()
{
        # we need to unload the driver and reload if we already configure once
        if [ -e /tmp/.already_configure_once ]; then
                switch_wireless_mode 14
        fi

	# make sure SSID and pass phrase is there
	setup_ap

        ifconfig ra0 up

        /sbin/ip addr add 192.168.10.100/24 dev ra0
	killall -9 udhcpd
        /usr/sbin/udhcpd /etc/udhcpd.conf
        touch /tmp/ap_mode
        touch /tmp/.already_configure_once

	# restart avahi to be safe
	/etc/init.d/avahi-daemon restart	
}

setup_interfaces()
{
	echo "Bring up all required interfaces: ra0 and apcli0"
	ifconfig ra0 up
	ifconfig apcli0 up
}

kill_udhcpc()
{
	# get the right pid then kill it
	pid=$(ps ax | grep udhcpc | grep $1 | head -n 1 | cut -d' ' -f1)
	if [ -z $pid ]; then
		killall -9 udhcpc
	else
	        kill -9 $pid
	fi
}

start_udhcpc()
{
	iface=$1

	if [ -z $iface ]; then
	   iface='apcli0'
	fi

	kill_udhcpc $iface
        sleep 1

        # start udhcpc
        udhcpc -R -b -p /var/run/udhcpc.$iface.pid -i $iface
}

switch_wireless_mode()
{
	ifconfig apcli0 down
        ifconfig ra0 down
	sleep 1
        rmmod mt_wifi

        sed -i "s/WirelessMode=.*$/WirelessMode=$1/g" /etc/wireless/mediatek/mt7663/mt7663.1.dat

        modprobe mt_wifi
        sleep 1

	ifconfig ra0 up
	ifconfig apcli0 up
	ifconfig ra0 down
}

restore_wireless_mode()
{

	# if we in AP mode put us back 
	if [ -e /tmp/ap_mode ]; then
		ap_mode
	elif [ $current_wmode'x' != $1'x' ]; then
                switch_wireless_mode $current_wmode
	fi
}

setup_scan()
{
        # $1 = mode- 9 for 2.4
        # 2.4GHz = 9
        # 5GHz = 14

	if [ $current_wmode'x' != $1'x' ]; then
		switch_wireless_mode $1
	fi


	if [ ! -e /sys/class/net/apcli0 ]; then
		ifconfig ra0 up
		ifconfig apcli0 up
	fi

        iwpriv apcli0 set PartialScan=0
        iwpriv apcli0 set SiteSurvey=
	sleep 1
        iwpriv apcli0 get_site_survey
}

connect_ssid()
{
        # $1 - SSID
        # $2 - Password
        # $3 - Security
	# $4 - Channel
	# $5 - nosave option 0|1 (1 is saved)

	channel=$4

        if [ -z $1 ]; then
                echo "No SSID specify"
                exit 1
        elif [ -z $2 ]; then
                echo "No passphrase specify"
                exit 1
	elif [ -z $3 ]; then
                echo "No security specify"
                exit 1
        fi

	ssid=$1
	pass=$2
	sec=$3

	auth_mode=${sec%%/*}
	enc_type=${sec##*/}

	ifconfig apcli0 up

	iwpriv apcli0 set ApCliEnable=0
	if [ ! -z $channel ]; then
		iwpriv apcli0 set Channel=$channel
		iwpriv ra0 set Channel=$channel

		if [ $channel -lt 12 ]; then
			wireless_mode=9
		        iwpriv apcli0 set WirelessMode=$wireless_mode
                        iwpriv ra0 set WirelessMode=$wireless_mode
		else
			wireless_mode=14
                        iwpriv apcli0 set WirelessMode=$wireless_mode
                        iwpriv ra0 set WirelessMode=$wireless_mode
		fi
		sleep 1
	fi

	iwpriv apcli0 set ApCliAuthMode=$auth_mode
	iwpriv apcli0 set ApCliEncrypType=$enc_type
	iwpriv apcli0 set ApCliSsid="$ssid"
	iwpriv apcli0 set ApCliWPAPSK="$pass"
	iwpriv apcli0 set ApCliSsid="$ssid"
	iwpriv apcli0 set ApCliEnable=1
	iwpriv apcli0 set ApCliAutoConnect=1
	sleep 5

	start_udhcpc apcli0

	# update profile
	sed -i "s/^ApCliAutoConnect=.*$/ApCliAutoConnect=1/" /etc/wireless/mediatek/mt7663/mt7663.1.dat
	sed -i "s/^Channel=.*$/Channel=$channel/" /etc/wireless/mediatek/mt7663/mt7663.1.dat
	sed -i "s/^WirelessMode=.*$/WirelessMode=$wireless_mode/" /etc/wireless/mediatek/mt7663/mt7663.1.dat
	sed -i "s/^ApCliAuthMode=.*$/ApCliAuthMode=$auth_mode/" /etc/wireless/mediatek/mt7663/mt7663.1.dat
	sed -i "s/^ApCliEncrypType=.*$/ApCliEncrypType=$enc_type/" /etc/wireless/mediatek/mt7663/mt7663.1.dat
	sed -i "s/^ApCliSsid=.*$/ApCliSsid=$ssid/" /etc/wireless/mediatek/mt7663/mt7663.1.dat
	sed -i "s/^ApCliWPAPSK=.*$/ApCliWPAPSK=$pass/" /etc/wireless/mediatek/mt7663/mt7663.1.dat
	sed -i "s/^ApCliEnable=.*$/ApCliEnable=1/" /etc/wireless/mediatek/mt7663/mt7663.1.dat


	# always save the profile, if $5 (nosave is 1) then do not save
	if [ ! -z $5 ] && [ $5 -eq 0 ]; then
	       save_profile
	fi
}

save_profile()
{
	# save profile to /media/extra/conf/network
	if [ ! -e /media/extra/conf/network ]; then
		mkdir -p /media/extra/conf/network
	fi
	cp -a /etc/wireless/mediatek/mt7663/mt7663.1.dat /media/extra/conf/network
}

disable_ap()
{
        ifconfig ra0 down
        killall -9 udhcpd
        rm -f /tmp/ap_mode
}

reset()
{
	disable_ap

	iwpriv apcli0 set ApCliSsid=
	iwpriv apcli0 set ApCliWPAPSK=
	iwpriv apcli0 set ApCliEnable=0

	# update profile
        sed -i "s/^Channel=.*$/Channel=/" /etc/wireless/mediatek/mt7663/mt7663.1.dat
        sed -i "s/^ApCliSsid=.*$/ApCliSsid=/" /etc/wireless/mediatek/mt7663/mt7663.1.dat
        sed -i "s/^ApCliWPAPSK=.*$/ApCliWPAPSK=/" /etc/wireless/mediatek/mt7663/mt7663.1.dat

	# Clear the IP then kill the udhcp process
	kill_udhcpc apcli0
        udhcpc -R -b -T 1 -p /var/run/udhcpc.apcli0.pid -i apcli0
	kill_udhcpc apcli0

	save_profile
}

reconnect()
{
	# restart network if it is set
	ssid=$(grep ApCliSsid /etc/wireless/mediatek/mt7663/mt7663.1.dat | cut -d= -f2)
	if [ ! -z "$ssid" ] ; then
		ifconfig apcli0 down
		ifconfig apcli0 up
		start_udhcpc apcli0

		save_profile
	fi
}


restore_network()
{
	ifconfig ra0 up
	ifconfig acplci0 up

	# when AP change channel we need to rescan and find the new channel to reconnect to 
	current_ssid=$(grep ApCliSsid= /etc/wireless/mediatek/mt7663/mt7663.1.dat | cut -d= -f2)

	if [ ! -z $current_ssid ]; then
		if [ -z $1 ] ; then
			if [ -z $current_wmode ]; then
				setup_scan 9
				setup_scan 14
			else
				setup_scan $current_wmode | grep $current_ssid
			fi
		else
			setup_scan $1 | grep $current_ssid
		fi

		iwpriv apcli0 set ApCliAutoConnect=1

		ifconfig ra0 down

		start_udhcpc apcli0

		save_profile
	fi
}

print_help()
{
	if [ -e /etc/wireless/mediatek/mtk_net_ctrl.help ]; then
	        /bin/cat /etc/wireless/mediatek/mtk_net_ctrl.help
	else
		echo "Available options"
	        echo -e "\t init - setup all required interfaces for use"
		echo -e "\t setup_ap - Setup Soft AP and bring it up"
		echo -e "\t disable_ap - Disable Soft AP"
		echo -e "\t ap_mode - Bring up Soft AP if it already setup"
		echo -e "\t scan24 - Site survey 2.4 GHz"
		echo -e "\t scan5 - Site survey 5 GHz"
		echo -e "\t site_survey - Site survey both 2.4GHz and 5GHz channel"
		echo -e "\t udhcpc - Start udhcpc"
		echo -e "\t connect - Connect to an AP"
		echo -e "\t\t $0 connect SSID PASSPHRASE SECURITY"
		echo -e "\t\t\t Example: $0 connect MySSID MyPassword WPA2PSK/AES"
	fi
}

# save the current wirless mode so we can restore it
current_wmode=$(grep WirelessMode /etc/wireless/mediatek/mt7663/mt7663.1.dat | cut -d= -f 2)

case "$opcode" in
	"init")
		setup_interfaces
		;;

        "setup_ap")
                setup_ap
                ap_mode
                ;;

        "ap_mode")
                ap_mode
                ;;

        "disable_ap")
		disable_ap
                ;;

         "scan24")
		 ( setup_scan 9 ) | tee /tmp/site_survey_results.txt 2>&1
		 restore_wireless_mode 9
                ;;

        "scan5")
		( setup_scan 14 ) | tee /tmp/site_survey_results.txt 2>&1
		restore_wireless_mode 14
                ;;

	"site_survey")
		### optimize the scan with the current Wireless mode
		### change band is costly currently ~8 seconds to switch band
		if [ $current_wmode'x' == '9x' ]; then
			( setup_scan 9 ) | tee /tmp/site_survey_results.txt 2>&1
			( setup_scan 14 ) | tee -a /tmp/site_survey_results.txt 2>&1
			restore_wireless_mode 14
		else
			( setup_scan 14 ) | tee /tmp/site_survey_results.txt 2>&1
			( setup_scan 9 ) | tee -a /tmp/site_survey_results.txt 2>&1
			restore_wireless_mode 9
		fi
		;;

	"set_wmode")
		shift
		switch_wireless_mode $1
		;;

	"get_wmode")
		echo $current_wmode
		;;

        "connect")
                shift
                connect_ssid $@
                ;;

	"reconnect")
                reconnect
                ;;

	"restore")
		# optional band 9 or 14
		shift
                restore_network $1
                ;;

	"reset")
                reset
                ;;

	"udhcpc")
		shift
		start_udhcpc $1
		;;

        *)
                echo -e "Invalid netv command. see help"
                print_help
                ;;
esac
