#!/bin/sh
#
# pulseaudio	This shell script starts and stops pulseaudio.
# Modified by Craig Matsuura (cmatsuura@vivint.com)
# Date: 7/7/2014s
# To work with the SkyControl Panel
#
# chkconfig: 345 90 40
# description: Pulseaudio manages the sound input/output
# processname: pulseaudio

# Source function library.
#. /etc/rc.d/init.d/functions

RETVAL=0
prog="pulseaudio"
START_STOP_OPTS="-m -p /var/run/pulse.pid -b"
#RESAMPLE_METHOD=trivial
RESAMPLE_METHOD=src-linear
#RESAMPLE_METHOD=speex-float-0
#RESAMPLE_METHOD=speex-fixed-0

start() {
    echo -n "Starting audio server: "
    start-stop-daemon -S $START_STOP_OPTS -x /usr/bin/pulseaudio -- \
    --system --disallow-exit --disallow-module-loading \
    --log-target=file:/var/log/pulse.log --high-priority --realtime \
    --no-cpu-limit --exit-idle-time=-1 --log-time -vvv --log-meta \
    --log-backtrace=5 --log-level=4 --resample-method=$RESAMPLE_METHOD \
    -nF /etc/pulse/session

    if [ $? = 0 ]; then
        echo "$prog (warning ignores)." # FIXME remove comment on warning
    else
        echo "(failed.)"
    fi
}

stop() {
    echo -n "Stopping audio server: "
    start-stop-daemon -K -x /usr/bin/pulseaudio
    echo "pulseaudio."
}

# See how we were called.
case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	stop
	sleep 1
	start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $RETVAL
