#! /bin/sh
# Copyright (c) 2017, Vivint.
#
# Check the IOT radios firmware and update if necessary
#set -x

platform=$(strings /proc/device-tree/compatible |
	grep vivint |
	sed s/^vivint,//)

if [ "$platform" != "brazen" ]; then
	exit 0;
fi

swd_search()
{
	for n in $(find /sys/class/mighty_gecko/*/name); do
		name=$(cat "$n")
	        swd=$(dirname "$n")

		if [ "$name"x = "zwavex" ]; then
			zwave_swd="$swd"
		elif [ "$name"x = "345x" ]; then
			efr32_swd="$swd"
		elif [ "$name"x = "bluetoothx" ]; then
			bluetooth_swd="$swd"
	        else
        	        echo "Unknown SWD"
	        fi
	done
}

get_zwave_fw()
{
	if [ -f /home/root/.mfg_image ]; then 
		echo "railtest_zwave.fw"
	else
		echo "vivint_zwave.fw"
	fi
}

get_bluetooth_fw()
{
	if [ -f /home/root/.mfg_image ]; then 
		echo "railtest_blue.fw"
	else
		echo "vivint_blue.fw"
	fi
}

flash_iot_fw()
{
	radio=$1
	fw_name=$2
	swd_path=$3
	echo "Check if $radio radio firmware is up to date, swd_path: $swd_path"
	if [ -f /tmp/"$radio"fwverified ]; then
		echo "$radio firmware already verified"
	elif [ -z "$swd_path" ]; then
	        echo "No SWD path for $radio"
	        return 1
	else
		echo "Flashing $radio firmware $fw_name ..."
		test -f "$swd_path"/access && echo 1 > "$swd_path"/access
			
		echo "$fw_name" > "$swd_path"/fw_path
		
		echo 1 > "$swd_path"/doall && touch /tmp/"$radio"fwverified
		test -f "$swd_path"/access && echo 0 > "$swd_path"/access
	fi
}

report()
{
	_failed=0
	if [ ! -e /tmp/zwavefwverified ]; then
		echo "Failed to update zwave firmware"
		(( _failed += 1 ))
	fi
	if [ ! -e /tmp/bluetoothfwverified ]; then
		echo "Failed to update bluetooth firmware"
		(( _failed += 1 ))
	fi
	if [ ! -e /tmp/efr32fwverified ]; then
		echo "Failed to update efr32 firmware"
		(( _failed += 1 ))
	fi

	return $_failed
}

case "$1" in
	start|restart|reload)
		if [ ! -d /sys/class/mighty_gecko ]; then
			echo "ERROR: Mighty Gecko kernel device driver not installed"
			exit 1
		fi

		swd_search
		flash_iot_fw "zwave" "$(get_zwave_fw)" "$zwave_swd"
		flash_iot_fw "efr32" "vivint_efr32.fw" "$efr32_swd"
		flash_iot_fw "bluetooth" "$(get_bluetooth_fw)" "$bluetooth_swd"
	
		wait
		report
		;;
	stop)
		stop
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
esac
