#!/bin/bash
### BEGIN INIT INFO
# Provides:          sendsigs
# Required-Start:    
# Required-Stop:     umountnfs
# Default-Start:
# Default-Stop:      0 6
# Short-Description: Kill all remaining processes.
# Description: 
### END INIT INFO

PATH=/sbin:/bin:/usr/sbin:/usr/bin
#set -x
#export PS4='+(${BASH_SOURCE}:${LINENO}): '

# SC-6389: We want all network-based services to be stopped before networking is stopped so that TCP close and FIN/ACK happens
INITIAL_SERVICES_TO_STOP="procmand $(cd /etc/procman.d/ && find . -maxdepth 1 -type f | tr '\n' ' ' | sed -e 's:./::g') pulseaudio"
echo "Stopping $INITIAL_SERVICES_TO_STOP"
for s in $INITIAL_SERVICES_TO_STOP ; do
    if test -f /etc/init.d/$s ; then
        /etc/init.d/$s stop &
    else
        killall -q -15 $s &
    fi
done
sleep 10

echo "Killing $INITIAL_SERVICES_TO_STOP"
for s in $INITIAL_SERVICES_TO_STOP ; do
    killall -q -9 $s &
done
sleep 1

# Now it should be okay to kill all processes, including networking
echo "Sending all processes the TERM signal... (`date`)"
killall5 -15 
sleep 10
sync
echo "Sending all processes the KILL signal..."
killall5 -9

: exit 0
