#!/bin/sh
VERSION="$(cat /etc/sly-version | head -n1 | awk '{print $2}')"
CODENAME="SkyHub"
BUILD_DATE=$(grep "Build Date" /etc/sly-version |awk '{print $3}')
OE_REV=$(grep "OERev" /etc/sly-version |awk '{print $2}')
APPS_REV=$(grep "AppsRev" /etc/sly-version |awk '{print $2}')
BUSYBOX_VERSION=$(busybox | head -n1 | awk '{ print $2}')
KERNEL_VERSION=$(uname -r)

case $1 in
"-v")
    echo "No LSB modules are available."
    ;;
"-i")
    echo "Distributor ID: Vivint."
    ;;
"-irc")
    echo "Distributor ID: Vivint."
    echo "Release:        $VERSION"
    echo "Codename:       $CODENAME"
    ;;
"-d")
    echo "Description:    SAWmill GNU/Linux $VERSION ($CODENAME)"
    ;;
"-r")
    echo "Release:        $VERSION"
    ;;
"-c")
    echo "Codename:       $CODENAME"
    ;;
"-a")
    echo "Distributor ID: Vivint."
    echo "Description:    SAWmill GNU/Linux $VERSION ($CODENAME)"
    echo "Busybox:        $BUSYBOX_VERSION"
    echo "Linux Kernel:   $KERNEL_VERSION"
    echo "Release:        $VERSION" 
    echo "Build Date:     $BUILD_DATE"
    echo "Codename:       $CODENAME"
    echo "OE Revision:    $OE_REV"
    echo "Apps Revision:  $APPS_REV"
    ;;
"-s")
    echo "No LSB modules are available."
    ;;
*)
    echo "Usage: lsb_release [options]"
    echo ""
    echo "Options:"
    echo "  -h, --help         show this help message and exit"
    echo "  -v, --version      show LSB modules this system supports"
    echo "  -i, --id           show distributor ID"
    echo "  -d, --description  show description of this distribution"
    echo "  -r, --release      show release number of this distribution"
    echo "  -c, --codename     show code name of this distribution"
    echo "  -a, --all          show all of the above information"
    echo "  -s, --short        show requested information in short format"
;;
esac
