#!/bin/sh
#
# ccat is colorcat
#
# Colors are defined by \033[31;47m
# Text Color red and Background color white
#
# 30 + n = Text color to use
# 40 + n = Background color to use
# Where n is:
#	0 = black
#	1 = red
#	2 = green
#	3 = yellow
#	4 = blue
#	5 = magenta
#	6 = cyan
#	7 = white
#	9 = Default Color
#

# If the user press Ctrl-C we need to reset the colors.
trap "echo -e '\033[39m'; exit" 0 1 2 15

cat $* | awk '
  /INFO/ {print "\033[32m" $0 "\033[39m"; break}
  /SEVERE/ {print "\033[31m" $0 "\033[39m"; break}
  /DEBUG/ {print "\033[33m" $0 "\033[39m"; break}
  /WARN/ {print "\033[34m" $0 "\033[39m"; break}
  /ERROR/ {print "\033[35m" $0 "\033[39m"; break}
  /./ {print $0 }
'


