#!/bin/bash
set -x

QUIET=no
SCRIPTNAME=$(basename "${BASH_SOURCE[0]}")
set -e

echo "$SCRIPTNAME"

modprobe board_info
BSPART=/dev/mmcblk0p3

# Utility functions
carp() {
	echo "$SCRIPTNAME: fatalerror: $1"
	exit 1
}

usage() {
	carp "usage: $SCRIPTNAME brazen | wallsly"
}

info() {
	test "$QUIET" == "yes" ||
		echo "$SCRIPTNAME: $1"
}

is_wallsly() {
	grep -q vivint,wallsly "/proc/device-tree/compatible"
}

is_brazen() {
	grep -q vivint,brazen "/proc/device-tree/compatible"
}

# The u-boot bootloader lives in the first eMMC boot partition, known in linux
# as /dev/mmcblk0boot0.  The u-boot environment lives in the second eMMC boot
# partition known in linux as /dev/mmcblk0boot1
#

# Utility functions to enable/disable writing to eMMC boot partitions
emmcrw() {
	local num=$1
	echo 0 > /sys/block/mmcblk0boot"${num}"/force_ro
}

emmcro() {
	local num=$1
	echo 1 > /sys/block/mmcblk0boot"${num}"/force_ro
}

# slimline and sly share a common u-boot binary
# wallsly has a specific version
ubootbinary() {
	is_wallsly &&
		echo "/boot/u-boot-brazen.imx" &&
		return
	is_brazen &&
		echo "/boot/u-boot-wallsly.imx" &&
		return

	carp "unsupported platform looking for u-boot binary"
}

#
ubootupdate() {
	confirmconversion

	emmcrw 0
	dd if=/dev/zero of=/dev/mmcblk0boot0 bs=1024 count=2048
	dd if="$(ubootbinary)" of=/dev/mmcblk0boot0 bs=512 seek=2

	sync
	emmcro 0

	# clearing u-boot env loses bootnum so leave it alone
	emmcrw 1
	dd if=/dev/zero of=/dev/mmcblk0boot1 bs=1024 count=2048
	emmcro 1
	
	info "board re-setup complete, reboot..."
	reboot -f

	exit 0
}

confirmconversion(){
	read -p "This will clear out all databases and logs. Do you want to continue? (Y/N)" yn
         case $yn in
                [Nn]* )
                        echo "Wussy... Exiting script"
                        exit 0
                        ;;
                [Yy]* )
                        echo "Deleting databases..."
                        rm -rf /media/extra/db/*
                        echo "Clearing out all logs..."
                        rm -rf /media/extra/log/*
                        ;;
                 * ) echo "Type Y for yes, N for no"; exit 0;;
        esac
}

if [ "$1" == "wallsly" ]; then
	is_brazen && ubootupdate
	echo 'Panel is already Wallsly'
else
	is_wallsly && ubootupdate
	echo 'Panel is already Brazen'
fi

exit 0
