#!/bin/bash

DEVPATH="$1"
DEVNAME=$(basename "$DEVPATH")
KEYPATH=/media/bootscript
KEYDEV=/dev/mmcblk2p1

mountpoint -q "$KEYPATH" || mount -o ro "$KEYDEV"

if [ ! -f "$KEYPATH/$DEVNAME-key.bb" ]; then
	echo "No encryption key available"
	exit 0
fi

# Check if we are mounting an encrypted device
MNTPNT=$(grep "$DEVNAME-encrypted" /etc/fstab | awk '{ print $2 }')
if [ -z "$MNTPNT" ]; then
	echo "No encrypted drive in fstab"
	exit 0
fi

caam-keygen import "$KEYPATH/$DEVNAME-key.bb" "$DEVNAME-key"

cat "/data/caam/$DEVNAME-key" | keyctl padd logon "$DEVNAME-key": @s

dmsetup -v create "$DEVNAME-encrypted" --table "0 $(blockdev --getsz "$DEVPATH") \
            crypt capi:tk(cbc(aes))-plain \
            ":36:logon:$DEVNAME-key:" 0 $DEVPATH 0 1 \
            sector_size:512"

# Make sure mount point is there
mkdir -p "$MNTPNT"
mount "/dev/mapper/$DEVNAME-encrypted"
