#!/bin/bash

DEVPATH="$1"
DEVNAME=$(basename "$DEVPATH")
KEYPATH=/media/bootscript
KEYDEV=/dev/mmcblk2p1

if [ -f "$KEYPATH/$DEVNAME"-key.bb ]; then
	echo "Encryption key already exists for dev $DEVNAME"
	exit 1
fi

systemctl stop procmand dect-audio syslog.socket openvpn@server baguette

set -e

if mountpoint -q /media/clips; then
	umount /media/clips
fi

if mountpoint -q /etc/ssl/certs; then
	umount /etc/ssl/certs
fi

swapoff /media/extra/swapfile || true

if mountpoint -q /media/extra; then
	umount /dev/mmcblk2p4
fi

caam-keygen create "$DEVNAME-key" ecb -s 16

mountpoint -q "$KEYPATH" || mount -o ro "$KEYDEV"
mount -o remount,rw,sync "$KEYPATH"
mv /data/caam/"$DEVNAME-key.bb" "$KEYPATH"
mount -o remount,ro "$KEYPATH"

cat "/data/caam/$DEVNAME-key" | keyctl padd logon "$DEVNAME-key": @s

dmsetup -v create "$DEVNAME"-encrypted --table "0 $(blockdev --getsz $DEVPATH) \
	crypt capi:tk(cbc(aes))-plain \
	":36:logon:$DEVNAME-key:" 0 $DEVPATH 0 1 \
       	sector_size:512"

mkfs.ext4 "/dev/mapper/$DEVNAME-encrypted"
mount "/dev/mapper/$DEVNAME-encrypted" /media/extra
