#!/bin/sh

CHANNEL=$1

procman suspend netd
echo ""
echo "ifconfig wlan1 down" > /dev/ttymxc1
echo "ifconfig wlan0 down" > /dev/ttymxc1
echo "iw dev wlan0 interface add mon0 type monitor" > /dev/ttymxc1
echo "ifconfig mon0 up" > /dev/ttymxc1

if [ -z $CHANNEL ]; then
  echo "iw mon0 set channel 1" > /dev/ttymxc1
  echo "Active receive started on channel 1"
elif [ $CHANNEL -ge 1 ] && [ $CHANNEL -le 11 ]; then
  echo "iw mon0 set channel $1" > /dev/ttymxc1
  echo "Active receive started on channel $1"
else
  echo "iw mon0 set channel 1" > /dev/ttymxc1
  echo "Active receive started on channel 1"
fi
echo "Reboot needed to restore WiFi"
echo ""
procman resume netd
