#!/bin/bash
#set -x

echo "fixing up procman.d..."
cd /mnt/mmcblk0p5/etc/
ls
mkdir .hidden
mv procman.d .hidden
mv procman.d-fcc procman.d 

echo "fixing up fonts..."
cd /mnt/mmcblk0p5/usr/lib/fonts
ls
mkdir .hidden
mv * .hidden/
mv .hidden/DejaVu* .
sync
exit 0
