#!/bin/bash
#set -x

echo "fixing up procman.d..."
cd /mnt/mmcblk0p5/etc/
mkdir .hidden
mv procman.d .hidden
mv procman.d-fcc procman.d 

echo "fixing up fonts..."
cd /mnt/mmcblk0p5/usr/lib/fonts
mkdir .hidden
mv * .hidden/
mv .hidden/DejaVu* .

echo "disabling psoc update"
cd /mnt/mmcblk0p5/etc/init.d
mv psoc5-verify psoc5-verify.orig
ln -s /bin/true psoc5-verify

sync
exit 0

