#! /bin/sh
# Copyright (c) 2015, Vivint.
#
# Initial setup on first boot at factory:
# Call /usr/local/bin/firstboot-setup to:
#    do initial board setup or subsequent board updates
#    see that file for details

firstboot()
{
	/usr/local/bin/firstboot-setup
}

do_nothing() {
	return 0
}

case "$1" in
	start)
		firstboot
		;;
	stop|restart|reload)
		do_nothing
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
esac

exit $?
