#! /bin/sh
# Copyright (c) 2015, Vivint.
#
# Initial setup on first boot at factory:
# Call /usr/local/bin/firstboot-setup to:
#    do initial board setup or subsequent board updates
#    see that file for details

firstboot()
{
	/usr/local/bin/firstboot-setup
}

is_brazen() {
        grep -q vivint,brazen "/proc/device-tree/compatible" &&
                test $(cat /sys/class/board_info/board_info/board_rev) -gt 13
}

run_led_status()
{
        /usr/local/bin/led_ctrl progress status white 255 &
}

do_nothing() {
	return 0
}

case "$1" in
	start)
		firstboot
		is_brazen && run_led_status
		;;
	stop|restart|reload)
		do_nothing
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
esac

exit $?
