#!/bin/sh
# init usb gadget for ethernet (rndis) and serial (acm)
#

mount -t configfs none /sys/kernel/config/
cd /sys/kernel/config/
modprobe libcomposite
cd usb_gadget/

# create multifunction gadget with two functions rndis(ethernet), acm(serial)
mkdir g1
cd g1
echo "0x1d6b" > idVendor	# linux foundation
echo "0x0104" > idProduct	# multifunction composite gadget
mkdir strings/0x409		# 409 is US english
echo "013456789" > strings/0x409/serialnumber
echo "Vivint." > strings/0x409/manufacturer
echo "Mfg Helper Gadget" > strings/0x409/product
mkdir functions/rndis.usb0
mkdir functions/acm.GS0

# Give rndis fixed dev(local) and remote(host) addresses:
#   Freescale OUI is 00-04-9f
#   Local address bit is 02-xx-xx... 
#   Rest could be random but use a fixed address so tools like network-manager
#   recognize the device as the same each time.
#   MBW: Base last 2 MAC bytes on board serial number. Multiple panels won't
#        conflict on same network and MAC value is consistent after rebooting
if [ -e /media/bootscript/serialnumber.txt ]; then
  serno="0x$(cat /media/bootscript/serialnumber.txt)"
  val1=$( printf "%02x" $[ $serno & 0xff ] )
  # Don't allow a 255 "broadcast" address to be used in the lsb
  if [[ $val1 -eq ff ]]; then
    val1=$( printf "%2x" 0xfe )
  fi
  [[ 0x$val1 -eq 0xff ]] && (( val1=0 ))
  val2=$( printf "%02x" $[ $[ $serno & 0xff00 ] >> 8 ] )
else
  val1='42'
  val2='00'
fi
echo 02:04:9f:1f:${val2}:${val1} > functions/rndis.usb0/host_addr
echo 02:04:9f:2f:${val2}:${val1} > functions/rndis.usb0/dev_addr

# create config with the two functions defined above
mkdir configs/c.1
mkdir configs/c.1/strings/0x409
echo "RNDIS + CDC ACM" > configs/c.1/strings/0x409/configuration
ln -s functions/rndis.usb0/ configs/c.1/
ln -s functions/acm.GS0 configs/c.1

# make it so -- this only works because there is only one udc
udcname=$(ls /sys/class/udc)
echo "$udcname" > UDC
