#!/usr/bin/env python3
#
# Copyright 2016 Vivint Innovation
#
# Used by manufacturer to generate a private/public keypair
#
# -
import os
import sys
import logging

import pysodium
from base64 import b64encode
import argparse
from subprocess import check_call, call
from taurine.utils.which_hardware import WhichHardware
from datetime import datetime


parser = argparse.ArgumentParser()
parser.add_argument('-l', '--key-location', nargs=1, default='/media/bootscript',
        help='Location where keys will be located', metavar='KEY_LOCATION')
args = parser.parse_args()

logger = logging.getLogger(__name__)

key_location = args.key_location
key_type = 'ed25519'
key_file = key_type
pk_file_path = key_location + '/id_' + key_type + '.pub'
sk_file_path = key_location + '/id_' + key_type
bootscript_partition = "/dev/mmcblk0p3"

def setup_logging():
    logging.basicConfig(level=logging.INFO,
                        format='%(asctime)s %(name)-12s %(levelname)-8s %(message)s',
                        datefmt='%Y-%m-%d %H:%M',
                        filename='/var/log/genkeys.log',
                        filemode='a')
    console = logging.StreamHandler()
    console.setLevel(logging.INFO)
    formatter = logging.Formatter("%(message)s")
    console.setFormatter(formatter)
    logging.getLogger('').addHandler(console)

def generate_keypair():
    # Check if the keys are already there
    if not os.path.isfile(pk_file_path) or not os.path.isfile(sk_file_path):
        logger.info('Generating keys...')
        pk, sk = pysodium.crypto_sign_keypair()
        pk = b64encode(pk).decode("ascii")
        sk = b64encode(sk).decode("ascii")

        # Write the keys
        pk_file = open(pk_file_path, 'w')
        pk_file.write(pk)
        pk_file.close()

        sk_file = open(sk_file_path, 'w')
        sk_file.write(sk)
        sk_file.close()
        os.chmod(sk_file_path, 0o600)

        logger.info('Successfully wrote keys to ' + key_location)
    else:
        # Read in the public key
        pk_file = open(pk_file_path, 'r')
        pk = pk_file.read()
        pk_file.close()
        logger.info('Loaded existing keys')

    logger.info('Public key: {}'.format(pk))
    logger.info('Date generated: {}'.format(datetime.fromtimestamp(os.path.getmtime(pk_file_path)).isoformat()))
    logger.info('Hardware type: {}'.format(WhichHardware.get_type()))

def mount_bootscripts(attr):
    return_code = call(["mount", "-o", "remount,{}".format(attr), bootscript_partition])
    if return_code != 0:
        check_call(["mount", "-o", attr, bootscript_partition])


setup_logging()

try:
    # First we remount the bootscript partition so we can write to it
    mount_bootscripts("rw")

    # Generate the keypair and write them to the filesystem if they don't already exist
    generate_keypair()

    # Remount the bootscript read only
    mount_bootscripts("ro")

except Exception:
    logger.exception("Unexpected error")
    sys.exit(1)

sys.exit(0)
