#!/bin/bash
BASEURL="http://updateseng.vivint.com/innovation/packages/branches/"
echo BASEURL is $BASEURL

SPRINTBRANCH=$(wget http://updateseng.vivint.com/innovation/packages/branches/ -O - 2>/dev/null | grep sprint  | sed -e 's/.*href="//' -e 's/\/.*//')
echo SPRINTBRANCH is $SPRINTBRANCH

LATESTSPRINT=$(wget http://updateseng.vivint.com/innovation/packages/branches/$SPRINTBRANCH -O - 2>/dev/null | grep href= | sed -e 's/.*href="//' -e 's/\/.*//' | grep sprint | sort -rn | head -n 1)
echo LATESTSPRINT is $LATESTSPRINT

FULLURL="${BASEURL}${SPRINTBRANCH}/${LATESTSPRINT}/sly-qt5-image-imx6dl-slimline-${LATESTSPRINT}.rootfs.tar.bz2"
echo FULLURL is $FULLURL

wget $FULLURL
