#!/bin/bash
#
# Description: This script is the production test for the Slimline panel camera
# A golden image is stored in /var/local/images/golden_image.jpg
# For convenience a golden image can be generated but should not in the case 
# of an actual production run
# On test, a new image will be generated and compared to the golden image
# We perform a mean error squared between the two images
# The comparison will pass if the error is less than a given threshold
#

retval=1
threshold=40
log_file=/tmp/test.log
diff_file=/tmp/diff.png
test_image=/tmp/test_image.jpg
golden_image_dir=/var/local/images
golden_image=/var/local/images/golden_image.jpg
golden_display_image=/var/local/images/golden_display_image.jpg
SCRIPTNAME=$(basename $BASH_SOURCE)
echo 1 > /sys/class/i2c-dev/i2c-3/device/3-0034/backlights/bl_backlight_blank

set +x
usage()
{
	echo "Usage: $SCRIPTNAME <option>"
	echo "   -c: Run video capture test" 
	echo "   -g: Generate new golden image"
	echo "   -d: Run display test"
	echo "  -gd: Generate new golden display image"
	echo "   -h: Show help options" 
}

display ()
{
	# Show pattern
	procman stop roubaix 2>&1 >/dev/null & 
	gst-launch-1.0 videotestsrc pattern=19 ! \
	"video/x-raw,width=1024,height=600" ! \
	imxipuvideosink > /dev/null 2>&1 &
	display_pid=$!
	disown

	# Capture view
	gst-launch-0.10 imxv4l2src num-buffers=1 ! \
	video/x-raw-yuv, framerate=30/1, width=640, height=480 ! \
	jpegenc ! filesink location=$test_image > /dev/null 2>&1
}

capture ()
{
	procman stop roubaix 2>&1 >/dev/null & 
	gst-launch-0.10 imxv4l2src num-buffers=1 ! \
	video/x-raw-yuv, framerate=30/1, width=640, height=480 ! \
	jpegenc ! filesink location=$test_image > /dev/null 2>&1
	gst-launch-1.0 filesrc location=$test_image blocksize=41700 ! \
	'image/jpeg' ! imxvpudec ! imagefreeze ! imxipuvideosink > /dev/null 2>&1 &
	capture_pid=$!
	disown
}

compare ()
{
	echo "Comparing new panel cam image with golden image"
	command compare.im6 -verbose -metric mse $1 $test_image $diff_file &> $log_file
	mse=`awk -F": " 'BEGIN { ORS="" } /all/ {print $2 }' < $log_file | cut -d' ' -f1 | cut -d'.' -f1`
	rm $log_file
	rm $diff_file

	# Test golden image with current against the fixed threshold
	if [ `printf '%d' "$mse"` -gt $threshold ];
	then
		retval=1
	else
		retval=0
	fi
}

if ! [ -e /usr/bin/compare.im6 ];
then
	echo "ImageMagick compare not installed"
	exit 1
fi

if [ "$1" == "-h" ];
then
	usage
elif [ "$1" == "-g" ];
then
	echo "Generating new golden image"
	capture
	echo "Setting new image to golden status"
	mkdir -p /var/local/images
	cp $test_image $golden_image
	echo "Success"
elif [ "$1" == "-gd" ];
then
	echo "Generating new golden display image"
	display
	echo "Setting new display image to golden status"
	mkdir -p /var/local/images
	cp $test_image $golden_display_image
	echo "Success"
elif [[ "$1" == "-c" && -e $golden_image ]];
then
	echo "Generating image"
	capture
	compare $golden_image
	if [ $retval == 1 ];
	then
		echo "FAIL"
	else
		echo "PASS"
	fi
elif [[ "$1" == "-d" && -e $golden_display_image ]];
then
	echo "Generating display image"
	display	
	compare $golden_display_image
	if [ $retval == 1 ];
	then
		echo "FAIL"
	else
		echo "PASS"
	fi
else
	if [ ! -e $golden_image ]
	then
		echo "There is no file" $golden_image
	fi
	if [ ! -e $golden_display_image ]
	then
		echo "There is no file" $golden_display_image
	fi
	usage
fi

read -p "Enter to Quit " yn
(kill $capture_pid 2>&1) > /dev/null &
(kill $display_pid 2>&1) > /dev/null &

set +x
