#!/bin/bash
#set -x

DEBUG=yes
#DEBUG=no
QUIET=no
SCRIPTNAME=$(basename $BASH_SOURCE)
set -e

echo "$SCRIPTNAME"

BSPART=/dev/mmcblk0p3

# Utility functions
carp() {
	echo "$SCRIPTNAME: fatalerror: $1"
	exit 1
}

usage() {
	carp "usage: $SCRIPTNAME no-clue?????"
}

info() {
	test "$QUIET" == "yes" ||
		echo "$SCRIPTNAME: $1"
}

debuginfo() {
	test "$DEBUG" == "yes" &&
		echo "$SCRIPTNAME: debug: $1"
}

## This script is only for a particular board
boardcheck() {
	grep -q vivint,slimline /proc/device-tree/compatible &&
		return 0
	grep -q vivint,sly /proc/device-tree/compatible &&
		return 0
	grep -q vivint,wallsly /proc/device-tree/compatible &&
		return 0
	grep -q vivint,brazen /proc/device-tree/compatible &&
		return 0
	carp "Unknown board type, exiting..."
}

#
# The bootscript and serial number are in the bootscript partition
#

# Some functions for (un)mounting the boot script partition
# read-only and read/write
#
mntbootscript()
{
	mount | grep -q ${BSPART} ||
		mount ${BSPART}
}

umntbootscript()
{
	mount | grep -q ${BSPART} &&
		umount ${BSPART}
}

mntbootscriptrw()
{
	umntbootscript || true
	mount ${BSPART} -o rw ||
		carp "unable to mount ${BSPART} read/write"
}

read_serial() {
	# 13 digits. The first three characters are allowed to be uppercase
	# alphanumeric. The remaining ten must be decimal digits.

	# Note: The panel uses bash 3.2, and so the regex must be in a variable.
	# This should also be compatible with more recent versions of bash.
	# Ref: https://stackoverflow.com/questions/15253792/bash-3-2-regex-pattern-not-matched-while-using

	alnum_regex="^[A-Z0-9]{3}[0-9]{10}$"
	while true; do
		local rawsn

		read -e -p "Enter Serialnumber: " rawsn
		if [[ $rawsn =~ $alnum_regex ]]; then
			SERIAL_NUMBER=$rawsn
			break
		else
			continue
		fi
	done
}

# prompt for a serial number and save it
serialnumset() {
	mntbootscriptrw

	clear; reset
	read_serial

	echo "${SERIAL_NUMBER}" > /media/bootscript/serialnumber2.txt

	# For backward compatability. If the serialnumber can be represented as
	# hex, also write it in the hex-formatted file that panel versions
	# prior to 3.19.3 understand
	decimal_regex="^[0-9]{13}$"
	if [[ $SERIAL_NUMBER =~ $decimal_regex ]]; then
		HEX_SERIAL_NUMBER="$(printf '%x' $(( 10#$SERIAL_NUMBER)) )"
		echo "${HEX_SERIAL_NUMBER}" > /media/bootscript/serialnumber.txt
	fi

	umntbootscript
	true
}

must_succeed()
{
	cmd=$1
	eval "${cmd}" &&
		info "${cmd} succeeded" &&
		return
	carp "${cmd} failed"
}

must_succeed boardcheck
serialnumset

info "Done setting serial number"

exit 0
