#!/bin/sh

arg=$1
device=''

if [[ `uname -a | cut -d' ' -f2` == "imx6dl-slimline" ]]
then
	device="This is Glance!"
fi

if [[ `uname -a | cut -d' ' -f2` == "imx6dl-skyhub" ]]
then
	device="This is Smart Hub!"
fi

if [[ `uname -a | cut -d' ' -f2` == "imx6dl-wallsly" ]]
then
	device="This is Smart Hub V2!"
fi

if [[ `uname -a | cut -d' ' -f2` == "imx6dl-brazen" ]]
then
	device="This is Brazen"
fi

if [[ $device == '' ]]
then
	echo "Panel type unknown. Now exiting..."
	exit 2
fi

echo $device

usage()
{
	echo "Usage:"
	echo "   'set-u-boot-part rw' to make the u-boot partition writable" 
	echo "   'set-u-boot-part ro' to make the u-boot partition read only" 
}

if [[ -z $arg ]]
then
	usage
	exit 1
fi

if [[ $arg == "rw" ]]
then
	echo "now setting the u-boot partition writable"
	echo 0 > /sys/block/mmcblk0boot1/force_ro
	exit 0
fi

if [[ $arg == "ro" ]]
then
	echo "now setting the u-boot partition read only"
	echo 1 > /sys/block/mmcblk0boot1/force_ro
	exit 0
fi

usage
