#!/bin/bash
set -x

hwclock --show

echo 1 > /sys/class/lm48511/lm485110/access
echo 0 > /sys/class/lm48511/lm485110/fb_sel
echo 0 > /sys/class/lm48511/lm485110/sd_amp
echo 0 > /sys/class/lm48511/lm485110/sd_boost
echo 0 > /sys/class/lm48511/lm485110/ss_ff

#echo 1 > /sys/power/pm_print_times
echo +30 > /sys/class/rtc/rtc0/wakealarm
echo mem > /sys/power/state

hwclock --show

