#!/bin/bash

echo 1 > /dev/vivint/psoc/backlights/bl_backlight_blank
export FB_MULTI_BUFFER=2
qmlfile=/tmp/touchtest.qml

pidof roubaix &> /dev/null
if [ $? == 0 ];
then
	procman stop roubaix 2>&1 /dev/null &
fi

S=$(cat <<EOF
import QtQuick 2.4
import QtQuick.Window 2.2
import "/opt/2gig/roubaix/views" as Views
import "/opt/2gig/roubaix/controls" as Buttons
import "/opt/2gig/roubaix/grids_lists" as Grids

Window {
    id: window
    visible: true
    width: 1024  
    height: 600  
                
    property bool top_left_touched: false
    property bool bottom_right_touched: false
    property int test_timeout: 1

    Item {
        Timer {
            id: timerDelay
            interval: 1000; running: true; repeat: true
            onTriggered: {
                test_timeout = test_timeout + 1
                if (top_left_touched && bottom_right_touched) {
                    Qt.quit()
                }

                if (test_timeout == 10) {
                    console.log("TIMEOUT!")
                    Qt.quit() 
                }
            }
        }
    }

   Rectangle {
       id: topleft
       width: 100; height: 100
       color: "red"

       anchors{                               
           top: parent.top              
           left: parent.left                
       }                                      

       MouseArea {
           anchors.fill: parent
           onClicked: {
               parent.color = 'green'
               top_left_touched = true
               if (bottom_right_touched) {                                                                             
                   console.log("PASSED!")
                   //Qt.quit()
               }
           }
       }
   }

   Rectangle {
       id: bottomright
       width: 100; height: 100
       color: "red"         
                              
       anchors{
           bottom: parent.bottom
           right: parent.right
       }

       MouseArea {
           anchors.fill: parent
           onClicked: {
               parent.color = 'green'
               bottom_right_touched = true
               if (top_left_touched) {
                   console.log("PASSED!")
                   //Qt.quit()
               }
           }
       }
   }

   Text {
       font.family: "Int Circular Pro Light"
       font.pixelSize: 20
       anchors.centerIn: parent
       text: "Vivint Touchscreen Production Test"
   }
}
EOF
)

echo -e "$S" > $qmlfile
/usr/bin/qt5/qmlscene $qmlfile
rm $qmlfile 
unset FB_MULTI_BUFFER
