#!/bin/bash

source /etc/profile.d/qt5.sh
export FB_MULTI_BUFFER=2
qmlfile=/tmp/touchtest.qml

pidof pumpernickel &> /dev/null
if [ $? == 0 ];
then
	procman stop pumpernickel 2>&1 /dev/null &
fi

if grep -q wallsly /proc/device-tree/compatible; then
	echo 0 > /sys/iodbus/lcd/lcd_power_off/value
	mxtfam=$(mxt-app -i | grep Family | awk '{print $2}')
	mxtver=$(mxt-app -i | grep Firmware | awk '{print $6}')
	if [ "$mxtfam" = '166' ]; then
		if [ "$mxtver" = "V1.0.AB" ]; then
			mxt-app --load /lib/firmware/maxtouch-wallsly_nvd.cfg
		elif [ "$mxtver" = "V1.0.AA" ]; then
			mxt-app --load /lib/firmware/maxtouch-wallsly_boe.cfg
		fi
	else
		mxt-app --load  /lib/firmware/maxtouch-wallsly_haier.cfg
	fi
else
	echo 1 > /sys/class/i2c-dev/i2c-3/device/3-0034/backlights/bl_backlight_blank
fi

S=$(cat <<EOF
import QtQuick 2.4
import QtQuick.Window 2.2
import "/opt/2gig/roubaix/views" as Views
import "/opt/2gig/roubaix/controls" as Buttons
import "/opt/2gig/roubaix/grids_lists" as Grids

Window {
    id: window
    visible: true
    width: 1024  
    height: 600  
                
    property bool top_left_touched: false
    property bool bottom_right_touched: false
    property int test_timeout: 1
    property int order: 1

    Item {
        Timer {
            id: timerDelay
            interval: 1000; running: true; repeat: true
            onTriggered: {
                test_timeout = test_timeout + 1
                if (top_left_touched && bottom_right_touched) {
                    Qt.quit()
                }

                if (test_timeout == 10) {
                    console.log("TIMEOUT!")
                    Qt.quit() 
                }
            }
        }
    }

   Rectangle {
       id: topleft
       width: 100; height: 100
       color: "red"

       anchors{                               
           top: parent.top              
           left: parent.left                
       }                                      

       MouseArea {
           anchors.fill: parent
           onClicked: {
               parent.color = 'green'
               top_left_touched = true
	       if (order < 4) {
	           order = order + 2
	       }
               if (bottom_right_touched) {                                                                             
		   if (order == 4) {
		       console.log("REVERSED!")
		   } else {
	   	       console.log("PASSED!")
		   }
               }
           }
       }
   }

   Rectangle {
       id: bottomright
       width: 100; height: 100
       color: "red"         
                              
       anchors{
           bottom: parent.bottom
           right: parent.right
       }

       MouseArea {
           anchors.fill: parent
           onClicked: {
               parent.color = 'green'
               bottom_right_touched = true
	       if (order < 4 ) {
	           order = order * 2
	       }
               if (top_left_touched) {
		   if (order == 4) {
		       console.log("REVERSED!")
		   } else {
                       console.log("PASSED!")
		   }
               }
           }
       }
   }

   Text {
       font.family: "Int Circular Pro Light"
       font.pixelSize: 20
       anchors.centerIn: parent
       text: "Vivint Touchscreen Production Test"
   }
}
EOF
)

echo -e "$S" > $qmlfile
ret=$(/usr/bin/qt5/qmlscene $qmlfile 2>&1)
if [ "$ret" == "qml: REVERSED!" ]; then
	if [ "$mxtfam" = '166' ]; then
		echo "qml: FAILED!"
	else
		mxt-app --load /lib/firmware/maxtouch-wallsly_tianma.cfg
		mxt-app --reset
		echo "qml: PASSED!"
	fi
else
	echo $ret
fi

rm $qmlfile 
unset FB_MULTI_BUFFER
