#!/bin/bash
#set -x

prep() {
        ps ax | grep -v grep | grep -q pumpernickel && killall -9 pumpernickel && sleep 5
        echo 1 > /dev/vivint/psoc/ambient/am_ambient_activate
        echo 0 > /sys/iodbus/lcd/lcd_power_off/value
        echo 1 > /dev/vivint/psoc/backlights/bl_backlight_blank
}

cleanup() {
        /etc/init.d/pumpernickel start
}

gensolids() {
        test -f /tmp/scrtest/red.rgba && return
        convert.im7 -size 1024x600 -depth 8 xc:#ffffff -fill '#ff0000' -draw "rectangle 0,0 1024,600" -depth 8 -endian MSB /tmp/scrtest/red.rgba
        convert.im7 -size 1024x600 -depth 8 xc:#ffffff -fill '#00ff00' -draw "rectangle 0,0 1024,600" -depth 8 -endian MSB /tmp/scrtest/green.rgba
        convert.im7 -size 1024x600 -depth 8 xc:#ffffff -fill '#0000ff' -draw "rectangle 0,0 1024,600" -depth 8 -endian MSB /tmp/scrtest/blue.rgba
        convert.im7 -size 1024x600 -depth 8 xc:#ffffff -fill '#ffffff' -draw "rectangle 0,0 1024,600" -depth 8 -endian MSB /tmp/scrtest/white.rgba
}

gengrad() {
        test -f /tmp/scrtest/top-bottom.rgba && return
        convert.im7 -size 1024x600 -define gradient:direction=north gradient:black-white -depth 8 -endian MSB /tmp/scrtest/top-bottom.rgba
        convert.im7 -size 1024x600 -define gradient:direction=north gradient:white-black -depth 8 -endian MSB /tmp/scrtest/bottom-top.rgba
}

dispall() {
        for g in red green blue white top-bottom bottom-top
        do
                cat /tmp/scrtest/$g.rgba /tmp/scrtest/$g.rgba > /dev/fb0
                read -t 10 foo
        done
        cleanup
}

dispone() {
        cat /tmp/scrtest/$1.rgba /tmp/scrtest/$1.rgba > /dev/fb0
}


mkdir -p /tmp/scrtest
gensolids
gengrad

prep
echo arg is $1
case "$1" in
        "red" | "green" | "blue" | "white" | "top" | "bottom" )
                dispone $1
                ;;
        "gray")
                dispone top-bottom
                ;;
        "clean")
                rm -rf /tmp/scrtest
                cleanup
                ;;
        * )
                dispall
                ;;
esac
