#! /bin/sh
# Copyright (c) 2017, Vivint.
#
# Check the Mighty Gecko firmware and update if necessary
#set -x

platform=$(strings /proc/device-tree/compatible |
	grep vivint |
	sed s/^vivint,//)

if [ "$platform" != "wallsly" ]; then
	return 0;
fi

mighty_gecko_verify()
{
	if [ ! -d /sys/class/mighty_gecko/swd0 ]; then
		echo "ERROR: Mighty Gecko kernel device driver not installed"
		return 1
	fi

	# if in fcc test mode use a different fw file
	if [ -f /etc/procman.d/test_ui ]; then
		if [ ! -e /lib/firmware/vivint/railtest_efr32.fw ]; then
			echo "ERROR: FCC firmware not found"
			return 1
		fi
	elif [ ! -e /lib/firmware/vivint/wallsly-mighty-gecko.fw ]; then
		echo "ERROR: Mighty Gecko firmware not found"
		return 1
	fi

	echo Check that Mighty Gecko firmware is up to date
	if [ -f /tmp/mightygeckofwverified ]; then
		echo "Mighty Gecko firmware already verified"
		return 0
	else
		test -f /sys/class/mighty_gecko/swd0/access &&
			echo 1 > /sys/class/mighty_gecko/swd0/access
		
		board_rev=$(cat /sys/class/board_info/board_info/board_rev)
		max_mighty_gecko_rev=13
		if [ "$board_rev" -gt "$max_mighty_gecko_rev" ]; then
			if [ -f /etc/procman.d/test_ui ]; then
				echo "Board revision number is $board_rev; Loading FFC firmware for FLEX gecko..."
				echo "railtest_efr32_flex1_uart.fw" > /sys/class/mighty_gecko/swd0/fw_path
			else
				echo "Board revision number is $board_rev; Loading wallsly-flex-gecko.fw for FLEX gecko..."
				echo "wallsly-flex-gecko.fw" > /sys/class/mighty_gecko/swd0/fw_path
			fi
		else
			if [ -f /etc/procman.d/test_ui ]; then
				echo "Board revision number is $board_rev; Loading FFC firmware for MIGHTY gecko..."
				echo "railtest_efr32.fw" > /sys/class/mighty_gecko/swd0/fw_path
			else
				echo "Board revision number is $board_rev; Loading wallsly-mighty-gecko.fw for MIGHTY gecko..."
				echo "wallsly-mighty-gecko.fw" > /sys/class/mighty_gecko/swd0/fw_path
			fi
			
		fi
		
		echo 1 > /sys/class/mighty_gecko/swd0/doall &&
			touch /tmp/mightygeckofwverified
		test -f /sys/class/mighty_gecko/swd0/access &&
			echo 0 > /sys/class/mighty_gecko/swd0/access
	fi

	return 0
}

case "$1" in
	start|restart|reload)
		mighty_gecko_verify
		;;
	stop)
		stop
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
esac
