#! /bin/sh
# Copyright (c) 2015, Vivint.
#
# Check the PSOC5 firmware and update if necessary
#set -x

platform=$(strings /proc/device-tree/compatible |
	grep vivint |
	sed s/^vivint,//)

if [ "$platform" == "wallsly" ]; then
	monpwr_module=monpwr_wall
	monpwr_devlink=/sys/bus/i2c/devices/1-0034
elif [ "$platform" == "sly" ]; then
	monpwr_module=monpwr_sly
	monpwr_devlink=/sys/bus/i2c/devices/3-0034
else
	monpwr_module=monpwr
	monpwr_devlink=/sys/bus/i2c/devices/3-0034
fi

# create a platform independent link to the monpwr psoc i2c device directory
mkdir -p /dev/vivint
rm -f /dev/vivint/psoc
ln -s $monpwr_devlink /dev/vivint/psoc


psoc5_verify()
{
	if [ ! -d /sys/class/swd/psoc50 ]; then
		echo "ERROR: PSOC5 kernel device driver not installed"
		return 1
	fi

	path=vivint/$platform-psoc5.fw
	# if sly use fcc version of fw if in fcc test mode
	# FIXME: do we have fcc fw from wallsly?
	if [ "$platform" == "sly" -a -f /etc/procman.d/test_ui ]; then
		path=vivint/$platform-fcc-psoc5.fw
	fi

	if [ ! -e /lib/firmware/$path ]; then
		echo "ERROR: PSOC5 firmware not found"
		return 1
	fi

	echo Check that PSOC 5 firmware is up to date
	if [ -f /tmp/psoc5fwverified ]; then
		echo "PSOC5 firmware already verified"
		return 0
	else
		monpwr_loaded=$(lsmod | grep monpwr | sed -e 's/ \+/\t/g' | cut -f 1)
		test "$monpwr_loaded" = "$monpwr_module" &&
			rmmod $monpwr_module
		test -f /sys/class/swd/psoc50/access &&
			echo 1 > /sys/class/swd/psoc50/access
		echo "echoing $path to fw_path"
		echo 1 > /sys/class/swd/psoc50/acquire
		echo $path > /sys/class/swd/psoc50/fw_path &&
			echo 1 > /sys/class/swd/psoc50/doall &&
			touch /tmp/psoc5fwverified
		test -f /sys/class/swd/psoc50/access &&
			echo 0 > /sys/class/swd/psoc50/access
	fi

	return 0
}

stop() {
	return 0
}

case "$1" in
	start|restart|reload)
		psoc5_verify
		monpwr_loaded=$(lsmod | grep monpwr | sed -e 's/ \+/\t/g' | cut -f 1)
		test "$monpwr_loaded" = "$monpwr_module" ||
			modprobe $monpwr_module
		;;
	stop)
		stop
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
esac

exit $?
