#! /bin/sh
# Copyright (c) 2015, Vivint.
#
# Check the PSOC5 firmware and update if necessary

psoc5_verify()
{
	# slimline only for now
	if ! grep -q vivint,slimline /proc/device-tree/compatible ; then
		echo "TODO: psoc verification on sly"
		return 0
	fi
	if [ ! -d /sys/class/swd/psoc50 ]; then
		echo "PSOC5 kernel device driver not installed"
		return 1
	fi

	if [ ! -e /lib/firmware/vivint/slimline-psoc5.fw ]; then
		echo "PSOC5 firmware not found"
		return 1
	fi

	echo Check that PSOC 5 firmware is up to date
	if [ -f /tmp/psoc5fwverified ]; then
		echo "PSOC5 firmware already verified"
		return 0
	else
		lsmod | grep -q monpwr && rmmod monpwr
		echo 1 > /sys/class/swd/psoc50/doall
		touch /tmp/psoc5fwverified
		modprobe monpwr
	fi

	return 0
}

stop() {
	return 0
}

case "$1" in
    start|restart|reload)
	psoc5_verify
	;;
    stop)
	stop
	;;
    *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
