#!/bin/sh
# Copyright (c) 2016, Vivint
#
# Update the zwave firmware on boot

zwave_program ()
{
    path=/lib/firmware/vivint/serialapi_controller_static_ZW050x_US.hex
    if [ ! -e $path ]; then
        echo "Zwave firmware not found"
        return 1
    fi

    if [ ! -e /opt/2gig/zwaved/scripts/zwave_program.pyo ]; then
        echo "Zwave programmer not found"
        return 1
    fi

    echo "Check that Zwave firmware is up to date"
    python3 /opt/2gig/zwaved/scripts/zwave_program.pyo $path
}

stop() {
    return 0
}

case "$1" in
    start|restart|reload)
    zwave_program
    ;;
    stop)
    stop
    ;;
    *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac

exit $?
