#!/bin/sh

EXEC='/usr/bin/schooner'
ARGS='--flagfile=/etc/schooner.config'
PIDFILE=/var/run/schooner.pid

case "$1" in
    start)
        chrt -i 0 ionice -c 2 -n 7 start-stop-daemon -S -b -m -p $PIDFILE -x $EXEC -- $ARGS
        sleep 1
        read PID <$PIDFILE
        echo 500 > /proc/$PID/oom_score_adj
        ;;
    stop)
        start-stop-daemon -K -p $PIDFILE
        ;;
    *)
        echo "Usage: $0 {start|stop}"
        exit 1
esac

exit 0
