#!/bin/sh

EXEC='/usr/bin/schooner'
ARGS='--flagfile=/etc/schooner.config'
PIDFILE=/var/run/schooner.pid

case "$1" in
    start)
        start-stop-daemon -S -b -m -p $PIDFILE -x $EXEC -- $ARGS
	sleep 1
	read PID <$PIDFILE
	chrt -i -p 0 $PID
	ionice -c 2 -n 7 -p $PID
        ;;
    stop)
        start-stop-daemon -K -p $PIDFILE
        ;;
    *)
        echo "Usage: $0 {start|stop}"
        exit 1
esac

exit 0
