#!/bin/sh

# EMB-14518
# Cell communication required a default route available for it to work.
# When wired or wireless network is not available, the default
# loopback route will be used.
# Routing table will pick the highest priority route which will be
# Wired / wireless network when available, loopback priority is the lowest.
# using metric 2000

is_nene() {
        grep -q vivint,nene "/proc/device-tree/compatible"
}

is_magellan() {
        grep -q vivint,magellan "/proc/device-tree/compatible"
}

is_yellowstone() {
        grep -q vivint,yellowstone "/proc/device-tree/compatible"
}

is_nene || is_magellan || is_yellowstone && {
	if ! ip route show default | grep "dev lo"
	then
		ip route add default dev lo metric 2000
	fi
}

exit 0
