#!/bin/sh
DAEMON=/usr/sbin/hostapd
NAME=hostapd
DESC="HOSTAP Daemon"
ARGS="/etc/hostapd.conf -B"

test -f $DAEMON || exit 0

set -e

# source function library
. /etc/init.d/functions


delay_stop() {
	count=0
	while [ $count -lt 9 ] ; do
	        if pidof $DAEMON >/dev/null; then
	                sleep 1
	        else
			killall -9 udhcpd
	                return 0
	        fi
		count=`expr $count + 1`
	done
	echo "Failed to stop $DESC."
	return 1
}

setup() {
    read macaddr </sys/class/net/wlan0/address
    read serialnum < /media/bootscript/serialnumber.txt
	macaddrup="$(echo $macaddr | tr '[:lower:]' '[:upper:]')"
    platform=$(strings /proc/device-tree/compatible | grep vivint | sed s/^vivint,//)
    password=$(echo -n $serialnum | sha256sum)

    if [ "$platform" == "brazen" ]; then
	    ARGS="/etc/hostapd_hub.conf -B"
        sed -i "s/ssid=.*/ssid=VIVINT_HUB_${serialnum}/" /etc/hostapd_hub.conf
        sed -i "s/wpa_passphrase=.*/wpa_passphrase=${password:0:63}/" /etc/hostapd_hub.conf
    else
        sed -i "s/ssid=.*/ssid=VIVINT_GLANCE_(${macaddrup:9})/" /etc/hostapd.conf
    fi

}

case "$1" in
    start)
	setup
	### HACK - maybe there a better way
	if [ "$platform" == "brazen" ]; then
		echo "Not auto start on Hub Plus"
		exit 0	
	fi

	echo -n "Starting $DESC: "
	start-stop-daemon -S -x $DAEMON -- $ARGS
	echo "$NAME."
	;;
    manual_start)
	setup
	echo -n "Starting $DESC: "
	start-stop-daemon -S -x $DAEMON -- $ARGS
	echo "$NAME."

	### HACK - this probably need to be move to udhcpd but add it here for now
	if [ "$platform" == "brazen" ]; then
		touch /var/lib/misc/udhcpd.leases
		udhcpd /etc/udhcpd.conf
		ifconfig wlan0 192.168.10.100
	fi
	;;

    stop)
	echo -n "Stopping $DESC: "
	start-stop-daemon -K --oknodo -x $DAEMON
	killall -9 udhcpd
	echo "$NAME."
	;;
    restart)
	$0 stop
	delay_stop && $0 start
	;;
    reload)
	echo -n "Reloading $DESC: "
	killall -HUP $(basename ${DAEMON})
	echo "$NAME."
	;;
    status)
	status $DAEMON
	exit $?
	;;
    *)
	echo "Usage: $0 {start|stop|restart|reload|status}"
	exit 1
	;;
esac

exit 0
