#!/bin/sh
DAEMON=/usr/sbin/ntpd
NAME=ntpd
DESC="Simple ntpd startup"

test -f $DAEMON || exit 0

set -e

case "$1" in
    start)
        echo -n "starting $DESC: $NAME... "

        start-stop-daemon -S -b -n $NAME -a $DAEMON -- -l
        echo "done."
        ;;
    stop)
        echo -n "stopping $DESC: $NAME... "
	start-stop-daemon -K -n $NAME
	echo "done."
	;;
    restart)
        echo -n "restarting $DESC: $NAME... "
	$0 stop
	$0 start
	echo "done."
	;;
    *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
	;;
esac

exit 0
