#!/bin/sh

{
if [ $# -ne 3 ]
then
	echo "Usage: $0 <client> mode ip" 
	echo "<client> is the CN name"
	echo "mode - client or all"
	echo -e "\tclient - only create client cert"
	echo -e "\tall - will create server key as well"
	echo "ip - remote host ip"
   	exit 0

fi

# create lock file - only allow one instance to run
echo
echo "##############################################"
date
echo
echo "Create call with: $1 $2 $3"

lock_dir="/var/lock/create_cam_vpn_cert"

if [ -e $lock_dir ]
then
	echo "Another process already run, quit"
	echo
	echo "#################################"
	exit 0
else
	echo "Create lock $lock_dir"
	mkdir -p $lock_dir
fi

client=$1
mode=$2
panel_ip=$3

base_dir=$(dirname $0)
cd $base_dir

work_dir=$(pwd)

. $work_dir/vars

sh $work_dir/clean-all

if [ $mode == "all" ]
then
   sh $work_dir/build-ca
   sh $work_dir/build-key-server server
else
   # copy ca.crt so we can tar up later
   cp /etc/openvpn/ca.crt $KEY_DIR
   cp /etc/openvpn/ca.key $KEY_DIR
fi

# build client cert
sh $work_dir/build-key $client

# rename client file to client.crt and client.key
mv $KEY_DIR/$client.crt $KEY_DIR/client.crt
mv $KEY_DIR/$client.key $KEY_DIR/client.key

if [ $mode == "all" ]
then
   sh $work_dir/build-dh

   # copy server.crt server.key ca.crt dh1024.pem /etc/openvpn
   cp $KEY_DIR/server.crt $KEY_DIR/server.key $KEY_DIR/ca.crt $KEY_DIR/ca.key $KEY_DIR/dh1024.pem /etc/openvpn
fi

cp $work_dir/client.ovpn $KEY_DIR

sed -i "s|::ip::|$panel_ip|" $KEY_DIR/client.ovpn
sed -i "s|::client_crt::|client.crt|" $KEY_DIR/client.ovpn
sed -i "s|::client_key::|client.key|" $KEY_DIR/client.ovpn

# make sure there is a remote ip ie. remote xxx.xxx.xxx.xxx 4194
grep -E -o "^remote ([0-9]{1,3}[\.]){3}[0-9]{1,3} 4194" $KEY_DIR/client.ovpn

if [ $? -eq 0 ]
then 
	# tar up client cert
	tar czvf $KEY_DIR/../${client}-${panel_ip}.tar.gz -C $KEY_DIR ca.crt client.crt client.key client.ovpn
else
	echo "Delete certs due to no remote ip in client.ovpn"
	rm -f $KEY_DIR/client.ovpn $KEY_DIR/client.crt $KEY_DIR/client.key $KEY_DIR/ca.crt
fi

echo
echo "Delete lock $lock_dir"
rm -rf $lock_dir
echo

} 2>&1 | tee -a /var/log/certGen.log

exit 0
