export BUILD_DIR=$1
# use "build" as the default build dir
: ${BUILD_DIR:=build}

_APPS_TAG="embedded-apps"
_APPS_REV='${AUTOREV}'
_APPS_BRANCH="develop"
_OPENWRT_BRANCH="check"

function whitewash_int {
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_UBOOT_SERVER"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_UBOOT_BRANCH"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_UBOOT_PROTOCOL"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_UBOOT_REV"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_WALLSLY_UBOOT_SERVER"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_WALLSLY_UBOOT_BRANCH"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_WALLSLY_UBOOT_PROTOCOL"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_WALLSLY_UBOOT_REV"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_KERNEL_SERVER"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_KERNEL_BRANCH"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_KERNEL_PROTOCOL"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_KERNEL_REV"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_AUDIO_SERVER"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_AUDIO_BRANCH"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_AUDIO_PROTOCOL"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_AUDIO_REV"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_APPS_SERVER"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_APPS_BRANCH"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_APPS_PROTOCOL"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_APPS_REV"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_MONPWR_BRANCH_SLIMLINE"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_MONPWR_BRANCH_SKYHUB"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_MONPWR_BRANCH_WALLSLY"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_MONPWR_SERVER_SLIMLINE"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_MONPWR_SERVER_SKYHUB"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_MONPWR_SERVER_WALLSLY"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_MONPWR_PROTOCOL_SLIMLINE"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_MONPWR_PROTOCOL_SKYHUB"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_MONPWR_PROTOCOL_WALLSLY"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_MONPWR_REV_SLIMLINE"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_MONPWR_REV_SKYHUB"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_MONPWR_REV_WALLSLY"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_ARTIFACTS_BRANCH"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_ARTIFACTS_SERVER"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_ARTIFACTS_PROTOCOL"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_ARTIFACTS_REV"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_SIMLOCK_SERVER"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_SIMLOCK_PROTOCOL"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_SIMLOCK_BRANCH"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_SIMLOCK_REV"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_META_VIVINT_BRANCH"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_META_VIVINT_REV"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_LIVE555_BRANCH"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_LIVE555_SERVER"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_LIVE555_PROTOCOL"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_LIVE555_REV"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_LIVE555PROXY_BRANCH"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_LIVE555PROXY_SERVER"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_LIVE555PROXY_PROTOCOL"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_LIVE555PROXY_REV"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_SERVER"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE LOCK_PORTS"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE REDUCE_LOGS"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_STRINGS_SERVER"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE SLIMLINE_VERSION"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE BY_PASS_UNIT_TEST"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE UPDATE_STRING_TABLE"
	export BB_ENV_EXTRAWHITE
}

# if already set up then we just run the setup-environment script
test -d ${BUILD_DIR} &&
	sed -i '/GIT_SERVER/d' ${BUILD_DIR}/conf/local.conf && 
	sed -i '/GIT_APPS_TAG/d' ${BUILD_DIR}/conf/local.conf &&
	sed -i '/GIT_APPS_REV/d' ${BUILD_DIR}/conf/local.conf && 
    sed -i '/GIT_APPS_BRANCH/d' ${BUILD_DIR}/conf/local.conf && 
	sed -i '/OPENWRT_BRANCH/d' ${BUILD_DIR}/conf/local.conf &&
	sed -i '/UPDATESENG/d' ${BUILD_DIR}/conf/local.conf && 
    sed -i '/PRSERV_HOST/d'  ${BUILD_DIR}/conf/local.conf && 
    sed -i '/DISTRO_FEATURES_remove/d' ${BUILD_DIR}/conf/local.conf && 
    sed -i '/IMAGE_INSTALL_remove/d' ${BUILD_DIR}/conf/local.conf && 
	echo "DISTRO_FEATURES_remove = \"x11 wayland directfb bluetooth zeroconf\"" >> ${BUILD_DIR}/conf/local.conf &&
	echo "IMAGE_INSTALL_remove = \" packagegroup-fsl-bluez5-tools\"" >> ${BUILD_DIR}/conf/local.conf &&
	echo "GIT_SERVER ?= \"git@source.vivint.com:7999/em\"" >> ${BUILD_DIR}/conf/local.conf &&
	echo "GIT_APPS_TAG ?= \"${_APPS_TAG}\"" >> ${BUILD_DIR}/conf/local.conf &&
	echo "GIT_APPS_REV ?= \"${_APPS_REV}\"" >> ${BUILD_DIR}/conf/local.conf &&
	echo "GIT_APPS_BRANCH ?= \"${_APPS_BRANCH}\"" >> ${BUILD_DIR}/conf/local.conf &&
	echo "OPENWRT_BRANCH ?= \"${_OPENWRT_BRANCH}\"" >> ${BUILD_DIR}/conf/local.conf &&
	echo "UPDATESENG ?= \"updateseng.vivint.com/innovation\"" >> ${BUILD_DIR}/conf/local.conf &&
    echo "PRSERV_HOST = \"localhost:0\"" >> ${BUILD_DIR}/conf/local.conf &&
	grep -q meta-vivint ${BUILD_DIR}/conf/bblayers.conf &&
	grep -q meta-oic ${BUILD_DIR}/conf/bblayers.conf &&
	source setup-environment ${BUILD_DIR} &&
	whitewash_int &&
	export BB_ENV_EXTRA_WHITE &&
	return

# it is a new dir
echo Setting up new dir \"${BUILD_DIR}\"
export MACHINE=imx6dl-slimline
export EULA=1
export DISTRO=slimline

if [ -z "$SLIMLINE_VERSION" ]; then
	export UPDATE_STRING_TABLE;
fi;

source ./fsl-setup-release.sh -b ${BUILD_DIR}

grep -q meta-vivint ./conf/bblayers.conf ||
	echo "BBLAYERS += \" \${BSPDIR}/sources/meta-vivint \"" \
		>> ./conf/bblayers.conf

grep -q meta-oic ./conf/bblayers.conf ||
    echo "BBLAYERS += \" \${BSPDIR}/sources/meta-oic \"" \
            >> ./conf/bblayers.conf

ln -s ../sstate-cache . || true

grep -q package_rpm ./conf/local.conf &&
	sed -i -e s/package_rpm/package_ipk/ ./conf/local.conf

grep -q DISTRO_FEATURES_remove ./conf/local.conf ||
	echo "DISTRO_FEATURES_remove=\"x11 wayland directfb bluetooth zeroconf\"" \
		>> ./conf/local.conf

grep -q IMAGE_INSTALL_remove ./conf/local.conf ||
    echo "IMAGE_INSTALL_remove=\" packagegroup-fsl-bluez5-tools\"" \
        >> ./conf/local.conf

sed '/iotivity-resource/d' ./conf/local.conf

grep -q GIT_SERVER ./conf/local.conf || 
	echo -e "GIT_SERVER ?= \"git@source.vivint.com:7999/em\"\nGIT_APPS_TAG ?= \"${_APPS_TAG}\"\nGIT_APPS_REV ?=\"${_APPS_REV}\"\nGIT_APPS_BRANCH ?= \"${_APPS_BRANCH}\"\nOPENWRT_BRANCH ?= \"${_OPENWRT_BRANCH}\"\nUPDATESENG = \"updateseng.vivint.com/innovation\"\nPRSERV_HOST = \"localhost:0\"" >> ./conf/local.conf

whitewash_int
export BB_ENV_EXTRA_WHITE 

