export BUILD_DIR=$1
# use "build" as the default build dir
: ${BUILD_DIR:=build-yellowstone}

function whitewash_int {
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_UBOOT_SERVER"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_UBOOT_BRANCH"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_UBOOT_PROTOCOL"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_UBOOT_REV"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_UBOOT_NGH_SERVER"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_UBOOT_NGH_BRANCH"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_UBOOT_NGH_PROTOCOL"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_UBOOT_NGH_REV"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_KERNEL_SERVER"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_KERNEL_BRANCH"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_KERNEL_NGH_BRANCH"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_KERNEL_PROTOCOL"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_KERNEL_REV"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_KERNEL_NGH_REV"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_AUDIO_SERVER"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_AUDIO_BRANCH"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_AUDIO_PROTOCOL"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_AUDIO_REV"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_APPS_SERVER"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_APPS_BRANCH"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_APPS_PROTOCOL"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_APPS_REV"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_APPS_TAG"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_ARTIFACTS_BRANCH"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_ARTIFACTS_SERVER"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_ARTIFACTS_PROTOCOL"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_ARTIFACTS_REV"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_ARTIFACTS_LATEST_BRANCH"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_ARTIFACTS_LATEST_SERVER"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_ARTIFACTS_LATEST_PROTOCOL"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_ARTIFACTS_LATEST_REV"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_DECT_CMD_SERVER"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_DECT_CMD_BRANCH"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_DECT_CMD_PROTOCOL"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_DECT_CMD_REV"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_SIMLOCK_SERVER"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_SIMLOCK_PROTOCOL"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_SIMLOCK_BRANCH"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_SIMLOCK_REV"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_META_VIVINT_BRANCH"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_META_VIVINT_REV"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_META_VIVINT_NGH_BRANCH"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_META_VIVINT_NGH_REV"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_LIVE555_BRANCH"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_LIVE555_SERVER"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_LIVE555_PROTOCOL"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_LIVE555_REV"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_LIVE555PROXY_BRANCH"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_LIVE555PROXY_SERVER"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_LIVE555PROXY_PROTOCOL"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_LIVE555PROXY_REV"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_LIVE555PROXY_NGH_BRANCH"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_LIVE555PROXY_NGH_SERVER"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_LIVE555PROXY_NGH_PROTOCOL"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_LIVE555PROXY_NGH_REV"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_DSPG_BRANCH"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_DSPG_SERVER"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_SERVER"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE LOCK_PORTS"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE REDUCE_LOGS"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_STRINGS_SERVER"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE SLIMLINE_VERSION"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE BY_PASS_UNIT_TEST"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE UPDATE_STRING_TABLE"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE BUILD_TYPE"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE CAMERA_PROTOBUF_BRANCH"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE CAMERA_PROTOBUF_SERVER"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE VIVINT_AIR_UTILS_BRANCH"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE VIVINT_AIR_UTILS_SERVER"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE TLS_PATH"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE WORK_PATH"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_HWD_SERVER"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_HWD_BRANCH"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_HWD_PROTOCOL"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_HWD_REV"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_ZGATE_SERVER"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_ZGATE_BRANCH_NGH"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_ZGATE_PROTOCOL"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_ZGATE_REV"

	export BB_ENV_EXTRAWHITE
}


# if already set up then we just run the setup-environment script
test -d ${BUILD_DIR} &&
	source setup-environment ${BUILD_DIR} &&
	whitewash_int &&
	export BB_ENV_EXTRA_WHITE &&	
	return

# If we fail the above, just re-create the conf/ files
rm -rf ${BUILD_DIR}/conf/
sed -i '/meta-rust/d' ./imx-setup-release.sh

# it is a new dir
echo Setting up new dir \"${BUILD_DIR}\"
export MACHINE=imx8mm-yellowstone
export EULA=1
export DISTRO=yellowstone-wayland

source ./imx-setup-release.sh -b ${BUILD_DIR}

grep -q meta-vivint ./conf/bblayers.conf ||
	echo "BBLAYERS += \" \${BSPDIR}/sources/meta-vivint \"" \
		>> ./conf/bblayers.conf

grep -q meta-wnc ./conf/bblayers.conf ||
    echo "BBLAYERS += \" \${BSPDIR}/sources/meta-wnc \"" \
            >> ./conf/bblayers.conf

grep -q meta-rust-bin ./conf/bblayers.conf ||
    echo "BBLAYERS += \" \${BSPDIR}/sources/meta-rust-bin \"" \
            >> ./conf/bblayers.conf

grep -q package_rpm ./conf/local.conf &&
	sed -i -e s/package_rpm/package_ipk/ ./conf/local.conf

whitewash_int
export BB_ENV_EXTRA_WHITE
