export BUILD_DIR=$1
# use "build" as the default build dir
: ${BUILD_DIR:=build}

function whitewash_int {
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_UBOOT_SERVER"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_UBOOT_BRANCH"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_UBOOT_PROTOCOL"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_UBOOT_REV"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_WALLSLY_UBOOT_SERVER"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_WALLSLY_UBOOT_BRANCH"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_WALLSLY_UBOOT_PROTOCOL"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_WALLSLY_UBOOT_REV"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_KERNEL_SERVER"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_KERNEL_BRANCH"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_KERNEL_PROTOCOL"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_KERNEL_REV"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_AUDIO_SERVER"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_AUDIO_BRANCH"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_AUDIO_PROTOCOL"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_AUDIO_REV"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_APPS_SERVER"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_APPS_BRANCH"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_APPS_PROTOCOL"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_APPS_REV"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_MONPWR_BRANCH_SLIMLINE"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_MONPWR_BRANCH_SKYHUB"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_MONPWR_BRANCH_WALLSLY"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_MONPWR_SERVER_SLIMLINE"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_MONPWR_SERVER_SKYHUB"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_MONPWR_SERVER_WALLSLY"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_MONPWR_PROTOCOL_SLIMLINE"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_MONPWR_PROTOCOL_SKYHUB"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_MONPWR_PROTOCOL_WALLSLY"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_MONPWR_REV_SLIMLINE"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_MONPWR_REV_SKYHUB"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_MONPWR_REV_WALLSLY"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_ARTIFACTS_BRANCH"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_ARTIFACTS_SERVER"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_ARTIFACTS_PROTOCOL"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_ARTIFACTS_REV"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_ARTIFACTS_LATEST_BRANCH"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_ARTIFACTS_LATEST_SERVER"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_ARTIFACTS_LATEST_PROTOCOL"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_ARTIFACTS_LATEST_REV"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_SIMLOCK_SERVER"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_SIMLOCK_PROTOCOL"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_SIMLOCK_BRANCH"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_SIMLOCK_REV"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_META_VIVINT_BRANCH"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_META_VIVINT_REV"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_LIVE555_BRANCH"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_LIVE555_SERVER"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_LIVE555_PROTOCOL"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_LIVE555_REV"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_LIVE555PROXY_BRANCH"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_LIVE555PROXY_SERVER"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_LIVE555PROXY_PROTOCOL"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_LIVE555PROXY_REV"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_SERVER"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE LOCK_PORTS"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE REDUCE_LOGS"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE GIT_STRINGS_SERVER"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE SLIMLINE_VERSION"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE BY_PASS_UNIT_TEST"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE UPDATE_STRING_TABLE"
	BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE BUILD_TYPE"
	export BB_ENV_EXTRAWHITE
}

# if already set up then we just run the setup-environment script
test -d ${BUILD_DIR} &&
	source setup-environment ${BUILD_DIR} &&
	whitewash_int &&
	export BB_ENV_EXTRA_WHITE &&	
	return

# it is a new dir
echo Setting up new dir \"${BUILD_DIR}\"
export MACHINE=imx8mm-nene
export EULA=1
export DISTRO=nene-wayland

source ./imx-setup-release.sh -b ${BUILD_DIR}

grep -q meta-vivint ./conf/bblayers.conf ||
	echo "BBLAYERS += \" \${BSPDIR}/sources/meta-vivint \"" \
		>> ./conf/bblayers.conf

grep -q meta-oic ./conf/bblayers.conf ||
    echo "BBLAYERS += \" \${BSPDIR}/sources/meta-oic \"" \
            >> ./conf/bblayers.conf

grep -q package_rpm ./conf/local.conf &&
	sed -i -e s/package_rpm/package_ipk/ ./conf/local.conf

whitewash_int
export BB_ENV_EXTRA_WHITE
