#!/bin/sh
set -e

PIDFILE=/var/run/chronyd.pid

test -x /usr/sbin/chronyd || exit 0
test -f /etc/chrony.conf || exit 0


case "$1" in
    start)
        echo "Starting chrony server: chronyd"
        start-stop-daemon -S -p $PIDFILE -x /usr/sbin/chronyd
        echo "done."
        ;;
    
    stop)
        echo -n "Stopping chrony server: chronyd"
        start-stop-daemon -K -p $PIDFILE -x /usr/sbin/chronyd
        echo "."
        ;;

    restart)
        echo -n "Restarting chrony server: chronyd"
        start-stop-daemon -K -p $PIDFILE --oknodo -x /usr/sbin/chronyd
        sleep 2
        start-stop-daemon -S -p $PIDFILE -x /usr/sbin/chronyd
        echo "."
        ;;

    *)
        echo "Usage: /etc/init.d/chrony {start|stop|restart}"
        exit 1
esac

exit 0

  /usr/sbin/chronyd
  echo "Started chronyd"
fi
