#!/bin/sh
#
#       Description     : network related parameters and functions
#			: (common between wired and wireless networks)
#       Original Author : Jerry Kuo
#	Modified by	: Matt Waddel (Vivint)
#
set -a

# Network parameters
IFACE_WIRED=${RE_IFACE_WIRED:-"eth0"}
IFACE_WIRELESS=${RE_IFACE_WIRELESS:-"wlan0"}
IFACE_VPN=${RE_IFACE_VPN:-"tap0"}
RALINK_TOKEN="RA"
REALTEK_TOKEN="RTL"
USE_IWPRIV=0
USE_WPASUPP=1
WIRED="wired"
WIRELESS="wireless"
WPS_TIMEOUT=120
WPS_HALF_TIMEOUT=60
WPS_IN_PROCESS="/tmp/wps_lock"

# Network config file path
DRIVER_DIR=${RE_DRIVER_DIR:-"/drivers"}
FIRMWAREVER_FILE="/etc/firmware-version"
INTERFACES_FILE="/etc/network/interfaces"
URL_ENCODE_SED="/etc/network/url_escape.sed"
WLAN_DRIVER_DIR=${RE_WLAN_DRIVER_DIR:-"/drivers"}
WLAN_MODULES="/etc/network/wlan_modules"
WIRELESS_CONF="/etc/network/wireless.conf"
WPA_SUPPLICANT_WIRELESS_CONF="/etc/network/wpa_supplicant_wireless.conf"

# Network services
SRV_DHCP6="/etc/init.d/dhcp6c"
SRV_DRM="/etc/init.d/drmd"
SRV_HTTP="/etc/init.d/httpd"
SRV_NETWORK="/etc/init.d/network"
SRV_RADVDUMP="/etc/init.d/radvdump"

# reconfig_network services lists
RECONFIG_SRVLIST_STOP="${SRV_DRM} ${SRV_HTTP} ${SRV_DHCP6}"
RECONFIG_SRVLIST_RESTART="${SRV_RADVDUMP} ${SRV_NETWORK}"
RECONFIG_SRVLIST_START="${SRV_DHCP6}"

# For wireless test
PROBE_IN_WIRED="/etc/network/probeinwired"
PROBE_WITH_VPN="/etc/network/probewithvpn"
RALINK_PCI_CONF="RT2860STA.dat"
RALINK_USB_CONF="RT2870STA.dat"
TIMEOUT_CGI=70
TIMEOUT_IW2=15
WAIT_KILLVPN=5
WAIT_CONN_NONE=5
WAIT_CONN_WEP=5
WAIT_CONN_WPA=15
WAIT_CONN_DEFAULT=30
WIRELESS_TEST="/usr/bin/wireless_test"
WIRELESS_TEST_CONF="/tmp/wireless_test.conf"
WIRELESS_TEST_RESULT="/var/run/wireless_test.log"
WIRELESS_TEST_QUERY="/var/run/wireless_test.query"
WLCONN_TEST="/usr/bin/wlconn_test"
WPA_SUPPLICANT_WIRELESS_TEST_CONF="/tmp/wpa_supplicant_wireless_test.conf"

# For site survey
SITE_SURVEY="/usr/bin/site_survey"
SITE_SURVEY_RESULT="/var/run/site_survey.log"

# Files in /var/run
LINK_STATUS="/var/run/linkstatus"
NETSTATUS="/var/run/netstatus"
WPA_SUPPLICANT_VAR="/var/run/wpa_supplicant"

# Script Path
CONFIG_LAN=${RE_CONFIG_LAN:-"/usr/bin/config-lan"}
CONFIG_WLAN=${RE_CONFIG_WLAN:-"/usr/bin/config-wlan"}
GEN_ETC_SAMBA_CONF=${RE_GEN_ETC_SAMBA_CONF:-"/usr/bin/gen_etc_samba_conf"}
IFSWITCH=${RE_IFSWITCH:-"/usr/bin/ifswitch"}
NETDRIVER=${RE_NETDRIVER:-"/usr/bin/netdriver"}

# Binary Path
ARPING="/usr/bin/arping"
AUTOIP="/usr/sbin/autoip"
CONFCLIENT="/usr/sbin/confclient"
CONFPARSER="usr/bin/confparser"
DUMPNETIF="/usr/sbin/dumpnetif"
ETHTOOL="/sbin/ethtool"
FIFOCMD="/usr/bin/fifocmd"
GETALIASIP="/usr/bin/getaliasip"
GREP="/bin/grep"
IFCONFIG="/sbin/ifconfig"
IFDOWN="/sbin/ifdown"
IFUP="/sbin/ifup"
IWCONFIG="/sbin/iwconfig"
IWLIST="/sbin/iwlist"
[ -x "/sbin/iwpriv" ] && IWPRIV="/sbin/iwpriv" || IWPRIV="/usr/bin/iwpriv"
KILLALL="/usr/bin/killall"
LEDCTRL="/usr/bin/ledctrl"
LINKDETECT="/usr/bin/linkdetect"
LOG_BIN="/usr/bin/logger"
MIITOOL="/sbin/mii-tool"
NOHUP="/usr/bin/nohup"
PARSENETIF="/usr/sbin/parsenetif"
PHYSETGET="/usr/sbin/phySetGet"
PHYDETECT="/usr/bin/phydetect"
ROUTE="/sbin/route"
SETDNS="/usr/sbin/setdns"
VCONFIG="/usr/bin/vconfig"
WPA_CLIENT="/usr/sbin/wpa_cli"
WPA_SUPPLICANT="/usr/sbin/wpa_supplicant"


# System functions
_find_max_string() {
        MAX=${MAX:-0}
        [ ${#1} -gt ${MAX} ] && MAX=${#1}
}

_find_max_value() {
        MAX=${MAX:-0}
        [ ${1} -gt ${MAX} ] && MAX=${1}
}

_array_put() {
    eval "$1_$2=\"\$3\""
}

_array_get() {
    eval "echo \${$1_$2}"
}

_array_get_dq() {
    eval "echo \"\${$1_$2}\""
}

_array_count() {
    set | ${GREP} "^$1_[0-9]*=" | wc -l
}

_count_array_num() {
    unset TOTAL_ITEMS
        local count
        let count=0
        while [ ${count} -lt ${1} ]
        do
                TOTAL_ITEMS=${TOTAL_ITEMS}" ${count}"
                count=$((count+1))
        done
}

_create_name_value_list() {
    local count
    let count=0
    while read line; do
        if echo "$line" | ${GREP} -q '^[a-zA-Z0-9]*[.-_]*[a-zA-Z0-9]*='; then
            VARNAME=`echo "${line}" | sed 's/=.*//'`
                        VALUE=`echo "${line}" | sed "s/${VARNAME}=//"`
                        _array_put LNAME ${count} "${VARNAME}"
            _array_put LVALUE ${count} "${VALUE}"
            count=$((count+1))
        fi
    done

    MAX_LVALUE_NUM=`_array_count LVALUE`
    _count_array_num ${MAX_LVALUE_NUM}
}

# Network related functions
_get_camera_model() {
        _start=1; _end=6
        FIRMWAREVER=`cat ${FIRMWARE_VER_FILE}`
        CAMERA_MODEL=`echo "${FIRMWAREVER}" | cut -c${_start}-${_end}`
}

_physetget() {
        if [ mf ${PHYSETGET} ]; then
                ${PHYSETGET} 2; ${PHYSETGET} 2 | ${GREP} 0x22
                if [ $? -eq 0 ]; then
                        HAS_PHY=1; echo "Ethernet PHY detected."
                else
                        HAS_PHY=0; echo "Cannot detect Ethernet PHY."
                fi
        else
                HAS_PHY=2 # phySetGet doesn't exist
        fi
}

_linkstatus() {
        echo "${1}" >> ${LINK_STATUS}
}

_linkdetect() {
#       _physetget
        HAS_PHY=1
        if [ ${HAS_PHY} -gt 0 ]; then
                if [ -x ${PHYSETGET} ] && [ -x ${PHYDETECT} ]; then
                        LINK_DETECT="${PHYDETECT}"
                elif [ -x ${ETHTOOL} ]; then
                        LINK_DETECT="${ETHTOOL} ${IFACE_WIRED}"
                else
                        LINK_DETECT="${MIITOOL}"
                fi
        else
                LINK_DETECT="NONE"
        fi

        LINK_DETECT="${ETHTOOL} ${IFACE_WIRED}"
}

_source_wireless_conf() {
        # Source wireless.conf file to get the stored info
        if [ -f ${WIRELESS_CONF} ];then
                . ${WIRELESS_CONF}
        else
                echo "Please generate ${WIRELESS_CONF} first!"
                exit 1
        fi
}

_source_wireless_test_conf() {
        if [ -f "${WIRELESS_TEST_CONF}" ];then
                . ${WIRELESS_TEST_CONF}
        else
                echo "Please generate ${WIRELESS_TEST_CONF} first"
                exit 1
        fi
}

_detect_wlan_module() {
        # Only support Realtek for now
        _create_name_value_list < ${WLAN_MODULES}
        # check if drivers exist
        DRIVERS=`ls ${DRIVER_DIR}`
        for i in ${TOTAL_ITEMS}
        do
                item0=`_array_get LNAME $i`
                item1=`_array_get LVALUE $i`
                IFDRIVER=${item1/ */}
                echo ${DRIVERS} | ${GREP} -q ${IFDRIVER//\"/}
                if [ $? -eq 0 ]; then
                        IFACENAME=${item0}
                        IFMODULE=${item1}
                        if echo ${IFACENAME} | ${GREP} -q ${REALTEK_TOKEN}
                        then
                                CMD_MODE=${USE_WPASUPP}
                                WLAN_MODULE="${REALTEK_TOKEN}"
                        else
                                CMD_MODE=${USE_WPASUPP}
                                WLAN_MODULE="${RALINK_TOKEN}"
                        fi
                        GOTIT_FLAG=1
                        break
                else
                        GOTIT_FLAG=0
                fi
        done

        # There is no active driver
        if [ ${GOTIT_FLAG} -eq 0 ]; then
                ${LOG_BIN} -t "[${0}]" -p $PRIORITY "${IFACENAME} driver doesn't exist"
                echo "${IFDRIVER} doesn't exist!"
        fi
}

_stop_linkdetect() {
        ps | ${GREP} 'linkdetect' | ${GREP} -v ${GREP}
        [ $? -eq 0 ] && ${KILLALL} -9 linkdetect
}

_start_linkdetect() {
        _stop_linkdetect
        ${IFCONFIG} ${IFACE_WIRELESS} down
        LINK_MODE=${1:-"dual"} # linkdetec has 3 modes; eth, wlan and dual
        ${LINKDETECT} -f /tmp/led.fifo -m ${LINK_MODE} &
}

_stop_udhcpc() {
        ${KILLALL} -9 udhcpc
}

_restart_network() {
        /etc/init.d/networking restart
}

_stop_wpa_supplicant() {
        ps | ${GREP} 'wpa_supplicant' | ${GREP} -v ${GREP}
        [ $? -eq 0 ] && ${KILLALL} -9 wpa_supplicant && sleep 2
}

_start_wpa_supplicant() {
        _stop_wpa_supplicant
        ${IFCONFIG} | ${GREP} -q ${IFACE_WIRELESS}
        [ $? -ne 0 ] && ${IFCONFIG} ${IFACE_WIRELESS} up
        ${WPA_SUPPLICANT} -Dwext -i ${IFACE_WIRELESS} -c ${WPA_SUPPLICANT_WIRELESS_CONF} -B
}

_start_wireless_test() {
        _stop_wpa_supplicant
        ${IFCONFIG} | ${GREP} -q ${IFACE_WIRELESS}
        [ $? -ne 0 ] && ${IFCONFIG} ${IFACE_WIRELESS} up
        ${WPA_SUPPLICANT} -Dwext -i ${IFACE_WIRELESS} -c ${WPA_SUPPLICANT_WIRELESS_TEST_CONF} -B
}

_shell_escape_byfile()
{
        echo "`sed \"s/\\\\\\/\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\/g\" < ${1}`" > ${1}
        echo "`sed \"s/\\\\$/\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\$/g\" < ${1}`" > ${1}
        echo "`sed \"s/\\\"/\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\"/g\" < ${1}`" > ${1}
        echo "`sed 's/\`/\\\\\\\\\\\`/g' < ${1}`" > ${1}
}
