#!/bin/sh

#make sure we have network wireless.conf and wpa_supplicant_wireless.conf
# symlink
media_extra_conf_network_dir="/media/extra/conf/network"

etc_wireless_conf="/etc/network/wireless.conf"
media_extra_wireless_conf="$media_extra_conf_network_dir/wireless.conf"

media_extra_wpa_supplicant_conf="$media_extra_conf_network_dir/wpa_supplicant_wireless.conf"
etc_wpa_supplicant_conf="/etc/network/wpa_supplicant_wireless.conf"

mkdir -p $media_extra_conf_network_dir

if [ ! -h $etc_wireless_conf ]
then
   echo "Create $etc_wireless_conf link"
   rm -f $etc_wireless_conf
   ln -sf $media_extra_wireless_conf $etc_wireless_conf
fi

if [ ! -h $etc_wpa_supplicant_conf ]
then
   echo "Create $etc_wpa_supplicant_conf link"
   rm -f $etc_wpa_supplicant_conf
   ln -sf $media_extra_wpa_supplicant_conf $etc_wpa_supplicant_conf
fi

exit 0

